### PR TITLE
Initial Setup

### PR DESCRIPTION
**Pull request by paddatrapper**
Sets up the basic manifest file and touches the created files.

### CODE REVIEW

**Comment by kzisme** [comment]
The only other thing I think we could use for an initial setup is a placeholder 19x19 or the image I asked about on irc.  

Your thoughts?

**Comment by paddatrapper** [comment]
I liked the one you asked about

**Comment by kzisme** [comment]
hntplaceholder

Here's the correct color to match their website - I didn't bother adding any logo or text just yet.  

Also - since you're not working on a branch (just master from what it looks like) I can't push the image to this PR right?  (Unless I just push it to the master branch - but I just wanted to keep all the initial stuff together)

**Comment by paddatrapper** [comment]
This is a PR from my fork, so you can push that to the master branch of this Repo with no problem. Or pull this in and then make a commit for the logo and then merge that into the master of this repo

**Comment by kzisme** [comment]
But I'm not able to push more commits to this PR right?

**Comment by paddatrapper** [comment]
No

**Comment by kzisme** [comment]
Thought so :) I'll merge this with master then add the image

**Comment by paddatrapper** [comment]
:+1:

**Pull request merged**
